### ISSUE TITLE
Some advice

### ISSUE THREAD

**Issue by prpanto** [GabrielaGodek/Portfolio#3]
Great job and thanks for some inspiration...

1. Use Nuxt a lot of benefits and better DX...
2. Use tailwindcss a lot of benefits and better DX...
3. Use computed function instead of onMounded to text rotate animation on image
```js
const textToRotate = computed(() => 'Your text here'
  .split('')
  .map((character, i) => `your code here`)
  .join(''));
```
4. Use `animate.js` on `hero__greeting__header` animation or [check](https://tobiasahlin.com/moving-letters/) this out.
5. Use `vueuse/motion` instead of css animation
6. I dont remember

If you want codes inspiration just tell...

**Comment by GabrielaGodek** [comment]
It is nice to get some feedback, thank you.
